### ISSUE TITLE
Remove unnecessary div and apply right css

### ISSUE THREAD

**Issue by Doha3ris** [Parrots-in-the-Alps/vulcan_hotel#2]
https://github.com/Parrots-in-the-Alps/vulcan_hotel/blob/0b6a35307a6ada601ef50b84a5740ec666ff3ca0/resources/js/App.vue#L3

Ça marche mais c'est pas terrible car même vide, une div est chargée dans le DOM et donc ralentie l'exécution de votre application. Ça vaudrait le coup de revoir l'utilisation des [flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/)

Les propriétés flex s'applique aux enfants de l'élément où elles sont déclarées. Pas besoin de div fantômes pour gérer l'espacement.

**Comment by NickelChr0me** [comment]
fix in [548f87bbc83759afb58bf95a670293769575e83d](https://github.com/Parrots-in-the-Alps/vulcan_hotel/commit/548f87bbc83759afb58bf95a670293769575e83d)
