### ISSUE TITLE
Use pinia to make HTTP request

### ISSUE THREAD

**Issue by Doha3ris** [Parrots-in-the-Alps/vulcan_hotel#3]
https://github.com/Parrots-in-the-Alps/vulcan_hotel/blob/0b6a35307a6ada601ef50b84a5740ec666ff3ca0/resources/js/components/Rooms.vue#L28

Pourquoi ne pas utiliser votre store pour faire vos appels HTTP ? C'est pourtant fais pour 🙃 Le store permet de stocker et rendre disponible des données spécifiques à toute l'application. En plus vous avez choisi [Pinia](https://pinia.vuejs.org/introduction.html#basic-example) qui est le top dans le milieu. (Bien plus simple d'utilisation que VueX à l'époque)

**Comment by NickelChr0me** [comment]
in progress
